#
# This LookML file was generated by AtScale on 2021-01-08T18:36:59.630197Z
#
# AtScale Egine Version: 2021.1.0.3350
# Organization: default
# Project: Sales Insights - BigQuery

connection: "atscale_server"
label: "Sales Insights - BigQuery"

include: "/views/default/Sales Insights - BigQuery (c16a8464-0fc3-4f8f-5af2-c61bcf3c21f6)/Internet Sales Cube (b89a2fb7-74f4-4828-706e-70f7186e10a0).view.lkml"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

