#
# This LookML file was generated by AtScale on 2020-08-03T20:58:48.724720Z
#
# AtScale Egine Version: 2020.4.0-SNAPSHOT
# Organization: default
# Project: Sales Insights - Snowflake 2

connection: "atscale_server"
label: "Sales Insights - Snowflake 2"

include: "/views/default/Sales Insights - Snowflake 2 (d7efe4c4-632c-4ddd-6747-cd71ad59fc96)/Internet Sales Cube (96e7012d-e3a1-495e-6dc8-3465080b28a6).view.lkml"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

