#
# This LookML file was generated by AtScale on 2020-12-28T17:53:59.827915Z
#
# AtScale Egine Version: 2021.1.0-SNAPSHOT
# Organization: default
# Project: Sales Insights - Snowflake

connection: "atscale_server"
label: "Sales Insights - Snowflake"

include: "/views/default/Sales Insights - Snowflake (eb37bd9f-4807-47be-6e5b-bc959bf87287)/Internet Sales Cube (b89a2fb7-74f4-4828-706e-70f7186e10a3).view.lkml"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

