#
# This LookML file was generated by AtScale on 2021-01-08T02:10:32.638836Z
#
# AtScale Egine Version: 2021.1.0-SNAPSHOT
# Organization: default
# Project: Sales Insights - BigQuery

connection: "atscale_server"
label: "Sales Insights - BigQuery"

include: "/views/default/Sales Insights - BigQuery (f4ba6794-54cd-4bb0-56ef-aba02ec91b50)/Internet Sales Cube (b89a2fb7-74f4-4828-706e-70f7186e10a0).view.lkml"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

