#
# This LookML file was generated by AtScale on 2020-05-19T18:57:22.850004Z
#
# AtScale Egine Version: 2020.3.0.1974
# Organization: default
# Project: Redshift Tickit Project

connection: "atscale_server"
label: "Redshift Tickit Project"

include: "/views/default/c0327536_146e_43de_7847_bbdd482a1ffe/c0327536-146e-43de-7847-bbdd482a1ffe.tickit_cube.view"

explore: Tickit_Cube {
    label: "Tickit Cube"
}

