#
# This LookML file was generated by AtScale on 2020-04-24T23:18:46.820965Z
#
# AtScale Egine Version: 2020.3.0.1897
# Organization: default
# Project: Sales Insights

connection: "atscale_server"
label: "Sales Insights"

include: "/views/default/19fd2b69_8112_461c_6f07_25262f1c3e83/sales_insights.internet_sales_cube.view"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

