#
# This LookML file was generated by AtScale on 2020-07-15T22:26:40.569768Z
#
# AtScale Egine Version: 2020.4.0-SNAPSHOT
# Organization: default
# Project: Sales Insights - Snowflake

connection: "atscale_server"
label: "Sales Insights - Snowflake"

include: "/views/default/4a27aea4_6c7a_4c98_41e0_0fcb2cd307d5/4a27aea4-6c7a-4c98-41e0-0fcb2cd307d5.internet_sales_cube___snowflake.view"

explore: Internet_Sales_Cube___Snowflake {
    label: "Internet Sales Cube - Snowflake"
}

