#
# This LookML file was generated by AtScale on 2020-04-30T03:51:28.261372Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Wayfair-AVAILABILITY CUBE

connection: "atscale_server"
label: "Wayfair-AVAILABILITY CUBE"

include: "/views/default/a5f51cc8_dbd0_45db_43a2_6b689022c23b/wayfair_availability_cube.availability_cube.view"

explore: Availability_Cube {
    label: "Availability Cube"
}

