#
# This LookML file was generated by AtScale on 2020-04-30T21:46:38.257908Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Wayfair-AVAILABILITY CUBE

connection: "atscale_server"
label: "Wayfair Cubes"

include: "/views/default/a5f51cc8_dbd0_45db_43a2_6b689022c23b/wayfair_availability_cube.availability_cube.view"

explore: Availability_Cube {
    label: "Availability Cube"
}

