#
# This LookML file was generated by AtScale on 2020-04-30T21:02:57.074557Z
#
# AtScale Egine Version: 2020.3.0.1898
# Organization: default
# Project: BCH

connection: "atscale_server"
label: "BCH"

include: "/views/default/a74ef246_6b5a_4699_5015_d07b4ced2ab0/bch.bch.view"

explore: BCH {
    label: "BCH"
}

