#
# This LookML file was generated by AtScale on 2021-02-04T17:14:18.076964Z
#
# AtScale Egine Version: 2021.1.0.3496
# Organization: 07adf2d9-bc80-480a-78ee-ca9defd8eb1f
# Project: Model for Demo - SNF

connection: "atscale_server"
label: "Model for Demo - SNF"

include: "/views/07adf2d9-bc80-480a-78ee-ca9defd8eb1f/Model for Demo - SNF (a73fea6f-61d6-4c9c-48fe-c3f363a5fd2b)/SNF Demo Cube (08c56fd9-f6e0-44cb-4e35-bc65a3437798).view.lkml"

explore: SNF_Demo_Cube {
    label: "SNF Demo Cube"
}

