#
# This LookML file was generated by AtScale on 2021-01-25T16:07:39.533648Z
#
# AtScale Egine Version: 2021.1.0.3350
# Organization: 07adf2d9-bc80-480a-78ee-ca9defd8eb1f
# Project: test

connection: "atscale_server"
label: "test"

include: "/views/07adf2d9-bc80-480a-78ee-ca9defd8eb1f/test (44b18a41-703c-468f-5a77-dff15bcd7dbb)/test (c31fa151-8296-45ca-752b-980039b514bd).view.lkml"

explore: test {
    label: "test"
}

