#
# This LookML file was generated by AtScale on 2020-07-13T23:43:45.712717Z
#
# AtScale Egine Version: 2020.4.0-SNAPSHOT
# Organization: default
# Project: Sales Insights - Synapse

connection: "atscale_server"
label: "Sales Insights - Synapse"

include: "/views/default/bfa70059_ac92_4967_68b5_b6404a8d5573/bfa70059-ac92-4967-68b5-b6404a8d5573.internet_sales_cube.view"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

