#
# This LookML file was generated by AtScale on 2020-05-22T17:22:51.425549Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Sales Insights - Big Query

connection: "atscale_server"
label: "Sales Insights - Big Query"

include: "/views/default/3f762923_59cf_4cda_46bf_1e5a4055794d/3f762923-59cf-4cda-46bf-1e5a4055794d.internet_sales_cube___bigquery.view"

explore: Internet_Sales_Cube___BigQuery {
    label: "Internet Sales Cube - BigQuery"
}

