#
# This LookML file was generated by AtScale on 2020-06-12T19:28:51.155590Z
#
# AtScale Egine Version: 2020.3.0.2002
# Organization: default
# Project: TPC-DS Benchmark Model - Synapse

connection: "atscale_server"
label: "TPC-DS Benchmark Model - Synapse"

include: "/views/default/8133ddcd_0149_4a49_70a3_392def0cbdab/8133ddcd-0149-4a49-70a3-392def0cbdab.tpc_ds_benchmark_model.view"

explore: TPC_DS_Benchmark_Model {
    label: "TPC-DS Benchmark Model"
}

