#
# This LookML file was generated by AtScale on 2020-04-21T18:42:53.066019Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: COVID-19
#

connection: "atscale_server"
label: "COVID-19"

include: "/views/default/4598323f_0776_47c9_46b6_c80fcec139b9/covid_19.covid_19_us.view"
include: "/views/default/4598323f_0776_47c9_46b6_c80fcec139b9/covid_19.covid_19_covidtracking_api_model.view"
include: "/views/default/4598323f_0776_47c9_46b6_c80fcec139b9/covid_19.covid_19_nyt_model.view"
include: "/views/default/4598323f_0776_47c9_46b6_c80fcec139b9/covid_19.covid_who.view"

explore: COVID_19_US {
    label: "COVID-19 US"
}

explore: COVID_19_CovidTracking_API_Model {
    label: "COVID-19 CovidTracking API Model"
}

explore: COVID_19_NYT_MODEL {
    label: "COVID-19 NYT MODEL"
}

explore: COVID_WHO {
    label: "COVID-WHO"
}

