#
# This LookML file was generated by AtScale on 2020-05-20T02:00:43.703849Z
#
# AtScale Egine Version: 2020.3.0.1974
# Organization: default
# Project: Tyson

connection: "atscale_server"
label: "Tyson"

include: "/views/default/ded93d34_638b_4c2b_501b_efcc423d2c48/ded93d34-638b-4c2b-501b-efcc423d2c48.tyson_cube.view"

explore: Tyson_Cube {
    label: "Tyson Cube"
}

