#
# This LookML file was generated by AtScale on 2020-06-01T21:15:16.940670Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Sales Insights

connection: "atscale_server"
label: "Sales Insights"

include: "/views/default/4ed16da1_47b3_4a4a_535b_80a186401d4b/4ed16da1-47b3-4a4a-535b-80a186401d4b.internet_sales_cube.view"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

