#
# This LookML file was generated by AtScale on 2020-05-20T21:38:42.318049Z
#
# AtScale Egine Version: 2020.3.0.1974
# Organization: default
# Project: Sales Insights - Big Query

connection: "atscale_server"
label: "Sales Insights - Big Query"

include: "/views/default/b83bf979_5edf_4b32_5da9_5e2fcc06069e/b83bf979-5edf-4b32-5da9-5e2fcc06069e.internet_sales_cube.view"

explore: Internet_Sales_Cube {
    label: "Internet Sales Cube"
}

