#
# This LookML file was generated by AtScale on 2020-05-22T17:25:51.362022Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Tyson

connection: "atscale_server"
label: "Tyson"

include: "/views/default/a250f748_8e7d_40c7_7490_eb08dd22cebc/a250f748-8e7d-40c7-7490-eb08dd22cebc.tyson_cube.view"

explore: Tyson_Cube {
    label: "Tyson Cube"
}

