#
# This LookML file was generated by AtScale on 2020-06-03T19:59:21.557570Z
#
# AtScale Egine Version: 2020.3.0.2002
# Organization: default
# Project: COVID-19

connection: "atscale_server"
label: "COVID-19"

include: "/views/default/4284b519_5f96_4dd7_7e1d_e299ed3b1bab/4284b519-5f96-4dd7-7e1d-e299ed3b1bab.covid_19_covidtracking_api_model.view"
include: "/views/default/4284b519_5f96_4dd7_7e1d_e299ed3b1bab/4284b519-5f96-4dd7-7e1d-e299ed3b1bab.covid_19_nyt_model.view"
include: "/views/default/4284b519_5f96_4dd7_7e1d_e299ed3b1bab/4284b519-5f96-4dd7-7e1d-e299ed3b1bab.covid_who.view"

explore: COVID_19_CovidTracking_API_Model {
    label: "COVID-19 CovidTracking API Model"
}

explore: COVID_19_NYT_MODEL {
    label: "COVID-19 NYT MODEL"
}

explore: COVID_WHO {
    label: "COVID-WHO"
}

