#
# This LookML file was generated by AtScale on 2020-04-30T00:46:14.281655Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Wayfairt-Service Executive Dashboard

connection: "atscale_server"
label: "Wayfair"

include: "/views/default/662b2c5c_84a0_43bd_66a7_65ec3369a1e8/wayfairt_service_executive_dashboard.service_executive_dashboard.view"

explore: Service_Executive_Dashboard {
    label: "Service Executive Dashboard"
}
