#
# This LookML file was generated by AtScale on 2020-06-13T00:04:38.216618Z
#
# AtScale Egine Version: 2020.3.0.2002
# Organization: default
# Project: TPC-DS Benchmark Model - Synapse

connection: "atscale_server"
label: "TPC-DS Benchmark Model - Synapse"

include: "/views/default/7fe79c15_7354_45ee_4ac8_ae261d6ac700/7fe79c15-7354-45ee-4ac8-ae261d6ac700.tpc_ds_benchmark_model.view"

explore: TPC_DS_Benchmark_Model {
    label: "TPC-DS Benchmark Model"
}

