#
# This LookML file was generated by AtScale on 2020-04-30T21:57:36.950270Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Wayfair-Supply Chain Cube

connection: "atscale_server"
label: "Wayfair Cubes"

include: "/views/default/f9295086_fcfe_450d_690d_f866d5c6bb9d/wayfair_supply_chain_cube.supply_chain_cube.view"

explore: Supply_Chain_Cube {
    label: "Supply Chain Cube"
}

