#
# This LookML file was generated by AtScale on 2020-04-29T17:36:46.025660Z
#
# AtScale Egine Version: 2020.3.0-SNAPSHOT
# Organization: default
# Project: Wayfair-MARGIN CUBE

connection: "atscale_server"
label: "Wayfair-MARGIN CUBE"

include: "/views/default/8a8e1d31_98d3_4e86_5477_a2383f5c6da1/wayfair_margin_cube.margin_cube.view"

explore: MARGIN_CUBE {
    label: "MARGIN CUBE"
}

