#
# This LookML file was generated by AtScale on 2020-05-18T22:34:19.183841Z
#
# AtScale Egine Version: 2020.3.0.1974
# Organization: default
# Project: Tyson

connection: "atscale_server"
label: "Tyson"

include: "/views/default/96d28d75_3821_47cd_5939_e4d834572c1c/96d28d75-3821-47cd-5939-e4d834572c1c.tyson.view"
include: "/views/default/96d28d75_3821_47cd_5939_e4d834572c1c/96d28d75-3821-47cd-5939-e4d834572c1c.cube_2.view"

explore: Tyson {
    label: "Tyson"
}

explore: Cube_2 {
    label: "Cube 2"
}

