#
# This LookML file was generated by AtScale on 2020-07-11T06:44:22.387889Z
#
# AtScale Egine Version: 2020.4.0.2295
# Organization: default
# Project: TPC-DS Benchmark Model - Synapse

connection: "atscale_server"
label: "TPC-DS Benchmark Model - Synapse"

include: "/views/default/006e04b5_3df5_46e9_7a80_06e8cdd9f982/006e04b5-3df5-46e9-7a80-06e8cdd9f982.tpc_ds_benchmark_model.view"

explore: TPC_DS_Benchmark_Model {
    label: "TPC-DS Benchmark Model"
}

