#
# This LookML file was generated by AtScale on 2020-06-13T04:34:43.642194Z
#
# AtScale Egine Version: 2020.3.0.2002
# Organization: default
# Project: TPC-DS Benchmark Model - Synapse

connection: "atscale_server"
label: "TPC-DS Benchmark Model - Synapse"

include: "/views/default/006e04b5_3df5_46e9_7a80_06e8cdd9f982/006e04b5-3df5-46e9-7a80-06e8cdd9f982.tpc_ds_benchmark_model.view"

explore: TPC_DS_Benchmark_Model {
    label: "TPC-DS Benchmark Model"
}

