#
# This LookML file was generated by AtScale on 2020-06-13T02:53:29.850086Z
#
# AtScale Egine Version: 2020.3.0.2002
# Organization: default
# Project: TPC-DS Benchmark Model - Synapse

connection: "atscale_server"
label: "TPC-DS Benchmark Model - Synapse"

include: "/views/default/5cf8e73a_3261_449c_7b22_a73faa24e721/5cf8e73a-3261-449c-7b22-a73faa24e721.tpc_ds_benchmark_model.view"

explore: TPC_DS_Benchmark_Model {
    label: "TPC-DS Benchmark Model"
}

