
#
# This LookML file was generated by AtScale on 2021-09-09T14:42:23.112623Z
#
# AtScale engine version: 2021.3.0.10800
# AtScale DesignCenter version: 2021.3.0.17842
# AtScale version: 2021.3.0.3811
# Organization: default
# Project: Sales Insights - Snowflake

connection: "atscale_server"
label: "Sales Insights - Snowflake"


include: "/views/Sales Insights - Snowflake/Internet Sales Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

