
#
# This LookML file was generated by AtScale on 2022-11-28T18:20:09.473595Z
#
# AtScale engine version: 2022.2.0.11610
# AtScale DesignCenter version: 2022.2.0.19507
# AtScale version: 2022.2.0.4819
# Organization: default
# Project: Sales Insights GBQ

connection: "atscale_al"
label: "Sales Insights GBQ"


include: "/views/Sales_Insights_GBQ/Internet_Sales_GBQ_Model.view.lkml"


explore: Internet_Sales_GBQ_Model {
  label: "Internet Sales GBQ Model"
}

