
#
# This LookML file was generated by AtScale on 2022-02-01T18:51:00.579054Z
#
# AtScale engine version: 2021.3.1.10910
# AtScale DesignCenter version: 2021.3.1.18398
# AtScale version: 2021.3.1.4032
# Organization: default
# Project: Sales Insights - Snowflake

connection: "atscale_server"
label: "Sales Insights - Snowflake"


include: "/views/Sales_Insights_-_Snowflake/Internet_Sales_Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

