
#
# This LookML file was generated by AtScale on 2021-09-14T21:33:08.360356Z
#
# AtScale engine version: 2021.3.0.10806
# AtScale DesignCenter version: 2021.3.0.17854
# AtScale version: 2021.3.0.3818
# Organization: default
# Project: Sales Insights - Snowflake

connection: "atscale_server"
label: "Sales Insights - Snowflake"


include: "/views/Sales Insights - Snowflake/Internet Sales Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

